// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var Verifier = artifacts.require('Verifier');
const zokratesProof = require("../../zokrates/code/square/proof.json");

contract('TestVerifier', accounts => {

    beforeEach(async() => {
        this.contract = await Verifier.new({from: accounts[0]});
    });

    // Test verification with correct proof
    // - use the contents from proof.json generated from zokrates steps
    it("Test verification with correct proof", async() => {
        let result = await this.contract.verifyTx.call(...Object.values(zokratesProof.proof), zokratesProof.inputs);
        assert.equal(result, true);
    });

    // Test verification with incorrect proof
    it("Test verification with incorrect proof", async() => {
        let result = await this.contract.verifyTx.call(...Object.values(zokratesProof.proof), [1, 2]);
        assert.equal(result, false);
    });
});
